# --------------------------------------------------------------------------- #
#                          VEHICLE PARAMETERS - BASIC                         #
# --------------------------------------------------------------------------- #
# This settings file contains the maneuverability parameters and constraints  #
# for a generic vehicle. These settings describe how the vehicle naturally    #
# moves between given waypoints. The purpose of this file is to provide a     #
# basic vehicle profile without imposing severe movement limitations.         #
# --------------------------------------------------------------------------- #

[Vehicle]

# The name for describing the vehicle model
vehicleName = Generic Aircraft				

averageSpeed = 100.0			   			# The scalar velocity of the vehicle (metres/sec)

maxTurnRate = 5.0    						# Maximum turn rate of vehicle (degrees/sec)
maxAcceleration = 2.0						# Maximum acceleration of vehicle (metres/sec^2)
maxDeceleration = 1.0						# Maximum deceleration of vehicle (metres/sec^2) (+ve for braking)

timeDelayAcceleration = 1.0 				# Time delay constant for acceleration/deceleration (seconds)
timeDelayTurning = 5.0						# Time delay constant for turning rates (seconds)

pitchConstantOffset = 0.0					# The constant pitch offset (degrees)
pitchOscPeriod = 0.0						# The pitch oscillation period (seconds)
pitchOscMagnitude = 0.0						# The pitch oscillation magnitude(degrees)
pitchMax = 90.0				    			# The maximum pitch limit (degrees)

rollConstantOffset = 0.0 					# The constant roll offset (degrees)
rollOscPeriod = 0.0 		 				# The roll oscillation period (seconds)
rollOscMagnitude = 0.0 						# The roll oscillation magnitude(degrees)
rollMax = 0.0								# The maximum roll limit (degrees)
rollTurnRate = -${rollMax}/${maxTurnRate} 	# The rolling turn rate (seconds)

vibrationNoiseAcceleration = 0.0 			# The vibration acceleration noise (m/s^2.sqrt(Hz))
vibrationNoiseAngleRates = 0.0				# The vibration angle rate noise (deg/s.sqrt(Hz))
vibrationDampingPeriod = 0.0				# The vibration dampening period (seconds)

variationsPerSecond1 = 0.0
variationsPerSecond2 = 0.0
