# --------------------------------------------------------------------------- #
#                          VEHICLE PARAMETERS - SHIP                          #
# --------------------------------------------------------------------------- #
# This settings file contains the maneuverability parameters and constraints  #
# for a large ship. These settings describe how a large ship, such as a cargo #
# vessel naturally moves between given waypoints. The purpose of this file is #
# to provide the expected movement limitations of a ship, accounting for slow #
# acceleration/deceleration and severe turning limitations.                   #
# --------------------------------------------------------------------------- #

[Vehicle]

# The name for describing the vehicle model
vehicleName = Large Ship	

averageSpeed = 11.00			   			# The scalar velocity of the vehicle (metres/sec)

maxTurnRate = 0.5    						# Maximum turn rate of vehicle (degrees/sec)
maxAcceleration = 0.1*9.81				    # Maximum acceleration of vehicle (metres/sec^2)
maxDeceleration = 0.1*9.81					# Maximum deceleration of vehicle (metres/sec^2) (+ve for braking)

timeDelayAcceleration = 2.0 				# Time delay constant for acceleration/deceleration (seconds)
timeDelayTurning = 2.0						# Time delay constant for turning rates (seconds)

pitchConstantOffset = 0.0					# The constant pitch offset (degrees)
pitchOscPeriod = 6.0						# The pitch oscillation period (seconds)
pitchOscMagnitude = 0.5						# The pitch oscillation magnitude(degrees)
pitchMax = 2.5				    			# The maximum pitch limit (degrees)

rollConstantOffset = 0.0 					# The constant roll offset (degrees)
rollOscPeriod = 10.0 		 				# The roll oscillation period (seconds)
rollOscMagnitude = 2.0 						# The roll oscillation magnitude(degrees)
rollMax = 5.0								# The maximum roll limit (degrees)
rollTurnRate = -${rollMax}/${maxTurnRate} 	# The rolling turn rate (seconds)

vibrationNoiseAcceleration = 0.05 			# The vibration acceleration noise (m/s^2.sqrt(Hz))
vibrationNoiseAngleRates = 0.5				# The vibration angle rate noise (deg/s.sqrt(Hz))
vibrationDampingPeriod = 1.0				# The vibration dampening period (seconds)
