# --------------------------------------------------------------------------- #
#                     VEHICLE PARAMETERS - GROUND VEHICLE                     #
# --------------------------------------------------------------------------- #
# This settings file contains the maneuverability parameters and constraints  #
# for a large ground vehicle. These settings describe how the ground vehicle  #
# naturally moves between given waypoints. Usually, a large ground vehicle    #
# such as a heavy van will have an average speed of around 40 mph, slow       #
# acceleration/deceleration and little turning limitations.					  #
# --------------------------------------------------------------------------- #

[Vehicle]

# The name for describing the vehicle model
vehicleName = Large Van			

averageSpeed = 17.88			   			# The scalar velocity of the vehicle (metres/sec)

maxTurnRate = 5.0    						# Maximum turn rate of vehicle (degrees/sec)
maxAcceleration = 0.25*9.81					# Maximum acceleration of vehicle (metres/sec^2)
maxDeceleration = 1.0*9.81					# Maximum deceleration of vehicle (metres/sec^2) (+ve for braking)

timeDelayAcceleration = 0.25 				# Time delay constant for acceleration/deceleration (seconds)
timeDelayTurning = 1.0						# Time delay constant for turning rates (seconds)

pitchConstantOffset = 0.0					# The constant pitch offset (degrees)
pitchOscPeriod = 0.0						# The pitch oscillation period (seconds)
pitchOscMagnitude = 0.0						# The pitch oscillation magnitude(degrees)
pitchMax = 33.0				    			# The maximum pitch limit (degrees)

rollConstantOffset = 0.0 					# The constant roll offset (degrees)
rollOscPeriod = 10.0 		 				# The roll oscillation period (seconds)
rollOscMagnitude = 2.0 						# The roll oscillation magnitude(degrees)
rollMax = 5.0								# The maximum roll limit (degrees)
rollTurnRate = -${rollMax}/${maxTurnRate} 	# The rolling turn rate (seconds)

vibrationNoiseAcceleration = 0.05 			# The vibration acceleration noise (m/s^2.sqrt(Hz))
vibrationNoiseAngleRates = 0.5				# The vibration angle rate noise (deg/s.sqrt(Hz))
vibrationDampingPeriod = 1.0				# The vibration dampening period (seconds)
