# --------------------------------------------------------------------------- #
#                        VEHICLE PARAMETERS - AIRCRAFT                        #
# --------------------------------------------------------------------------- #
# This settings file contains the maneuverability parameters and constraints  #
# for a large aircraft. These settings describe how the air vehicle, such as  #
# a cargo plane, naturally moves between given waypoints. These parameters    #
# are supplied for a 737 type of air-vehicle, stating slow acceleration and   #
# deceleration with wide turning.                                             #
# --------------------------------------------------------------------------- #

[Vehicle]

# The name for describing the vehicle model
vehicleName = Large Aircraft

averageSpeed = 50.0			   			    # The scalar velocity of the vehicle (metres/sec)

maxTurnRate = 10.0    						# Maximum turn rate of vehicle (degrees/sec)
maxAcceleration = 0.2*9.81				    # Maximum acceleration of vehicle (metres/sec^2)
maxDeceleration = 0.1*9.81					# Maximum deceleration of vehicle (metres/sec^2) (+ve for braking)

timeDelayAcceleration = 0.5 				# Time delay constant for acceleration/deceleration (seconds)
timeDelayTurning = 0.5						# Time delay constant for turning rates (seconds)

pitchConstantOffset = 2.0					# The constant pitch offset (degrees)
pitchOscPeriod = 0.0						# The pitch oscillation period (seconds)
pitchOscMagnitude = 0.0						# The pitch oscillation magnitude(degrees)
pitchMax = 45.0				    			# The maximum pitch limit (degrees)

rollConstantOffset = 0.0 					# The constant roll offset (degrees)
rollOscPeriod = 0.0 		 				# The roll oscillation period (seconds)
rollOscMagnitude = 0.0 						# The roll oscillation magnitude(degrees)
rollMax = 25.0								# The maximum roll limit (degrees)
rollTurnRate = 2.5 	                        # The rolling turn rate (seconds)

;vibrationNoiseAcceleration = 0.05 			# The vibration acceleration noise (m/s^2.sqrt(Hz))
;vibrationNoiseAngleRates = 0.5				# The vibration angle rate noise (deg/s.sqrt(Hz))
;vibrationDampingPeriod = 1.0				# The vibration dampening period (seconds)

vibrationNoiseAcceleration = 0.0 			# The vibration acceleration noise (m/s^2.sqrt(Hz))
vibrationNoiseAngleRates = 0.0				# The vibration angle rate noise (deg/s.sqrt(Hz))
vibrationDampingPeriod = 1.0				# The vibration dampening period (seconds)

variationsPerSecond1 = 0.005
variationsPerSecond2 = 0.01