# -----------------
# Example GPS Zones
# -----------------
# This sub-configuration file gives examples for defining custom GPS zones.
# Whether GPS is assumed to be accessible globally is set with 'gpsActiveByDefault'.
# The coordinates for defining zone polygons are set with 'gpsZoneCoordinates'.
# Using these, whether GPS is usable or unusable is determined by setting
# either a 1 or 0 in 'gpsZoneActive' respectively.

[GpsZones]

;Should the GPS be active by default?
gpsActiveByDefault = yes

;Define zones as list of latitude-longitude coordinates.
;A new line must be given for each zone. Each polygon is closed automatically.
gpsZoneCoordinates =
    53.381166, -2.335227, 53.381166, -2.135227, 53.581166, -2.135227, 53.581166, -2.335227, 53.381166, -2.335227
    53.26164 , -3.150065, 53.26164 , -2.850065, 53.56164 , -2.850065, 53.56164 , -3.150065, 53.26164 , -3.150065
    53.228079, -1.624052, 53.228079, -1.324052, 53.528079, -1.324052, 53.528079, -1.624052, 53.228079, -1.624052

;Define the zones which are active and inactive.
;Use 0 or 1 values, corresponds to the zone list given above.
gpsZoneActive = 0, 0, 0
