# --------------------------------------------------------------------------- #
#                       ACCELEROMETER SETTINGS - CUSTOM                       #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for the       #
# system clock. These are typical/expected values used for testing.           # 
# --------------------------------------------------------------------------- #

[Clock]
clockBiasDriftRate = 0.0                   		# (nano-sec/root sec)
clockInitialStaticBiasMean = 0.0           		# (standard deviation)
