# --------------------------------------------------------------------------- #
#                        SYSTEM CLOCK SETTINGS - MARINE                       #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for the       #
# system clock. This given configuration is used to simulate the accuracy     #
# and reliability expected from marine graded hardware.                       #
# --------------------------------------------------------------------------- #

[Clock]
clockBiasDriftRate = 1.0                   		# (nano-sec/root sec)
clockInitialStaticBiasMean = 1.0           		# (standard deviation)
