# --------------------------------------------------------------------------- #
#                       SYSTEM CLOCK SETTINGS - TACTICAL                      #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for the       #
# system clock. This given configuration is used to simulate the accuracy     #
# and reliability expected from tactical graded hardware.                     #
# --------------------------------------------------------------------------- #

[Clock]
clockBiasDriftRate = 5.0                 		# (nano-sec/root sec)
clockInitialStaticBiasMean = 5.0           		# (standard deviation)
