# --------------------------------------------------------------------------- #
#                       ACCELEROMETER SETTINGS - AVIATION                     #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for an        # 
# accelerometer. This given configuration is used to simulate the accuracy    #
# expected from Aviation graded hardware.                                     #
# --------------------------------------------------------------------------- #

[Accelerometer]
accelerometerBiasDriftRate = 1.0                    	# (micro-g/root sec)
accelerometerScaleErrorMean = 10                      	# (ppm)
accelerometerMeasurementError = 15                   	# (micro-g.root Hz)
accelerometerNonOrthogonalityMean = 10              	# (micro-radians)
accelerometerInitialStaticBiasMean = 30              	# (micro-g)
