# --------------------------------------------------------------------------- #
#                    ACCELEROMETER SETTINGS - INTERMEDIATE                    #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for an        # 
# accelerometer. This given configuration is used to simulate the accuracy    #
# expected from intermediate (between Aviation and Tactical) graded hardware. #
# --------------------------------------------------------------------------- #

[Accelerometer]
accelerometerBiasDriftRate = 2.0                    	# (micro-g/root sec)
accelerometerScaleErrorMean = 100                      	# (ppm)
accelerometerMeasurementError = 40                   	# (micro-g.root Hz)
accelerometerNonOrthogonalityMean = 100              	# (micro-radians)
accelerometerInitialStaticBiasMean = 100              	# (micro-g)
