# --------------------------------------------------------------------------- #
#                       ACCELEROMETER SETTINGS - MARINE                       #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for an        # 
# accelerometer. This given configuration is used to simulate the accuracy    #
# expected from marine graded hardware.                                       #
# --------------------------------------------------------------------------- #

[Accelerometer]
accelerometerBiasDriftRate = 0.05                    	# (micro-g/root sec)
accelerometerScaleErrorMean = 1                      	# (ppm)
accelerometerMeasurementError = 5                   	# (micro-g.root Hz)
accelerometerNonOrthogonalityMean = 10              	# (micro-radians)
accelerometerInitialStaticBiasMean = 10              	# (micro-g)
