"""
======
run.py
======

:summary:
    Main execution script for the Quantum Navigation Toolbox.
    The script provides a level of command-line interfacing with the toolbox.
    This is required for parsing the given input commands, importing attached
    configuration files, and then producing the resulting output.

:authors:
    | Prof Jason Ralph - jfralph@liverpool.ac.uk
    | Michael Wright - mjwright@liverpool.ac.uk

:version:
    1.1.0 - Included summary with writing results
"""

# Required to ensure qnav is on path!
import sys; from pathlib import Path
import shutil
src_path = Path(__file__).parent / 'src'
sys.path.append(str(src_path))

import qnav.input.config as cfg
import qnav.simulation.simulation as sim
import qnav.output.figures as plot

from qnav.input.config_handler import ConfigHandler
from qnav.input.raw import is_raw_mode
from qnav.simulation.replay import ReplayResults, run_raw_replay
from qnav.simulation.results import ResultsCapture
from qnav.output.summary import write_summary_file
from qnav.output.formats import save_as
from qnav.output.data import ResultsTable
from qnav import __version__ as qnav_version

from typing import Optional
from warnings import warn


def parse_args() -> Optional[Path]:
    """
    Parse command line arguments.
    Returns the filepath given by the first command line argument (after the
    application name). If no arguments are given, then None is returned.

    :return: File given as first command line argument (or None if not given).
    :rtype: Optional[Path]
    """
    return None if len(sys.argv) <= 1 else Path(sys.argv[1])


def read_config(config_file: Path) -> ConfigHandler:
    """
    Reads and returns the initialised configuration for given file.
    Attempts to read the

    :param config_file: The configuration file to use.
    :type config_file: Path

    :return:  The config handler instance to use for parameter values.
    :rtype: ConfigHandler
    """
    return cfg.get_configuration(config_file)


def run_simulation(config: ConfigHandler) -> ResultsCapture | ReplayResults:
    """
    Executes the simulation for the given configuration file settings.
    Uses the given configuration file to set up the described simulation
    and then execute it. On succession, the captured results will be
    returned.

    :param config: The config handler instance to use for parameter values.
    :type config: ConfigHandler

    :return: The results generated by the simulation.
    :rtype: ResultsCapture
    """

    if is_raw_mode(config):
        cfg.print_banner("Raw Sensor Replay")
        return run_raw_replay(config)

    # Initialise the simulation components
    trajectory = cfg.get_trajectory(config)
    estimated_state = cfg.get_estimation(config, trajectory)
    hardware = cfg.get_platform_hardware(config, estimated_state)
    clock = cfg.get_platform_clock(config)
    results = cfg.get_collector(config)
    display = cfg.get_displayer(config)

    try:

        # Execute the simulation
        cfg.print_banner("Simulation")
        sim.run_simulation_loop(
            trajectory,
            estimated_state,
            hardware,
            clock,
            results,
            display
        )

    except AssertionError as ae:
        warn(f'AssertionError: {ae}')
        print('Stopping simulation early')

    # Return the results
    return results


def _clear_previous_results(output_dir: Path) -> None:
    """Remove artifacts produced by an earlier run in this directory."""
    for stem in ("estimation", "ground_truth"):
        for path in output_dir.glob(f"{stem}.*"):
            if path.is_file():
                path.unlink()
    for name in (
        "ingestion_report.json",
        "summary.json",
        "processed_accelerometer.csv",
        "processed_gyroscope.csv",
        "config.ini",
        "config_full.ini",
    ):
        path = output_dir / name
        if path.is_file():
            path.unlink()
    figures = output_dir / "figures"
    if figures.is_dir():
        shutil.rmtree(figures)


def save_results(config: ConfigHandler,
                 results: ResultsCapture | ReplayResults) -> Path:
    """
    Save and export simulation results to disk.
    Extracts the gathered simulation results and saves them to disk,
    using the requested settings.

    :param config: The config handler instance to use for parameter values.
    :type config: ConfigHandler

    :param results: The results generated by the simulation.
    :rtype: ResultsCapture

    :return: The directory path where results were saved to.
    :rtype: Path
    """

    # Extract the requested settings.
    settings = cfg.get_results_settings(config)
    save_summary = settings['save_summary']
    copy_config = settings['copy_config']
    output_dir = settings['output_dir']
    formats = settings['formats']
    ds = settings["down_sampling"]

    _clear_previous_results(output_dir)

    # Specify where results are to be saved.
    estimates_file = output_dir / 'estimation.qnr'
    estimates_table = ResultsTable(estimates_file)
    true_data_table = None

    # Include copy of configuration file if requested:
    if copy_config:
        config.copy_file(output_dir / "config.ini")
        config.write_file(output_dir / "config_full.ini")

    # Export the results in the requested formats.
    if isinstance(results, ReplayResults):
        results.write(estimates_table)
        results.write_report(output_dir / 'ingestion_report.json')
        results.write_processed_imu(output_dir)
        if results.reference:
            truth_file = output_dir / 'ground_truth.qnr'
            candidate_table = ResultsTable(truth_file, auto_load=False)
            results.write_reference(candidate_table)
            true_data_table = candidate_table
    else:
        truth_file = output_dir / 'ground_truth.qnr'
        true_data_table = ResultsTable(truth_file)
        results.save(estimates_table, true_data_table)

    save_as(output_dir, 'estimation', estimates_table, ds, *formats)
    if true_data_table is not None:
        save_as(output_dir, 'ground_truth', true_data_table, ds, *formats)

    # Include summary results of simulation if requested:
    if save_summary:
        summary_file = output_dir / 'summary.json'
        write_summary_file(summary_file, config, estimates_table, true_data_table)

    # Generate all result figures and graphs (if requested).
    generate_figures(config, output_dir, estimates_table, true_data_table)

    # Lastly, return where results are saved to
    return output_dir


def generate_figures(config: ConfigHandler,
                     output_dir: Path,
                     estimates_table: ResultsTable,
                     true_data_table: ResultsTable = None) -> None:
    """
    Generates report figures for simulation results.
    Can be called after a simulation to display its results in graphs and
    figures. Requires both captured estimated and ground truth records.

    :param config: The configuration instance being used for.
    :type config: ConfigHandler

    :param output_dir: The output directory to save figures to.
    :type output_dir: Path

    :param estimates_table: The estimated state records from the simulation.
    :type estimates_table: ResultsTable

    :param true_data_table: The ground truth records from the simulation.
    :type true_data_table: ResultsTable
    """

    # Extract the requested settings.
    settings = cfg.get_figure_settings(config)
    save_figs = settings['do_save']
    show_figs = settings['do_show']
    renderer = settings['renderer']
    formats = settings['formats']

    if not save_figs and not show_figs:
        return

    # Generate and extract figure information.
    figure_data = plot.generate_all_figures(
        estimates_table, true_data_table)
    figs = figure_data['figures']
    titles = figure_data['titles']
    sizes = figure_data['sizes']

    # If figures are to be saved:
    if save_figs:

        # Create any missing folders.
        fig_dir = output_dir / 'figures'
        if not fig_dir.exists():
            fig_dir.mkdir(parents=True)

        # Save each figure for each requested format.
        for fig, name, size in zip(figs, titles, sizes):
            for fmt in formats:
                fig.write_image(fig_dir / f"{name}.{fmt}", **size, scale=2)

    # If figures are to be displayed:
    if show_figs:

        # Render each using the requested renderer.
        for fig in figs:
            fig.show(renderer=renderer, config={'displaylogo': False})


if __name__ == '__main__':
    """
    Called when the script is executed directly.
    This is the entry point when using the software from the command-line.
    On execution, reads the configuration file given in the command-line 
    arguments (or uses the default) and completes a typical simulation.
    """

    # Display some information at start-up
    print(f"Starting Quantum Navigation Toolbox...")
    print(f"Software Version: {qnav_version}")

    input_file = parse_args()
    configuration = read_config(input_file)
    data = run_simulation(configuration)
    results_dir = save_results(configuration, data)
    cfg.print_banner()

    if results_dir is not None:
        print(f"Results saved to: '{results_dir}'")
