# --------------------------------------------------------------------------- #
#                            QUANTUM IMU SETTINGS                             #
# --------------------------------------------------------------------------- #
# This settings file contains the configuration values for the quantum IMU.   #
# --------------------------------------------------------------------------- #

[Quantum]

quantumImuFrequency = 1.0		            # The total operating frequency of the sensor (Hz).
quantumImuDutyCycle = 0.5		            # Percentage of time the sensor is active (measuring).


; --------------- Quantum IMU accelerometer parameters --------------- ;

quantumAccXEnabled = yes
quantumAccYEnabled = yes
quantumAccZEnabled = yes

quantumAccBiasDriftRate = 0.0               # The quantum accelerometer's drift rate (micro-g/root sec)
quantumAccScaleErrorMean = 0.0              # The quantum accelerometer's average scale error (ppm)
quantumAccMeasurementError = 0.0            # The quantum accelerometer's measurement error (micro-g.root Hz)
quantumAccNonOrthogonalityMean = 0.0        # The quantum accelerometer's non-orthogonal mean error (micro-radians)
quantumAccInitialStaticBiasMean = 0.0       # The quantum accelerometer's initial static bias error (micro-radians/sec)


; --------------- Quantum IMU gyroscope parameters --------------- ;

quantumGyroXEnabled = yes
quantumGyroYEnabled = yes
quantumGyroZEnabled = yes

quantumGyroBiasDriftRate = 0.0              # The quantum gyroscope's drift rate (micro-rad/sec.root sec)
quantumGyroScaleErrorMean = 0.0             # The quantum gyroscope's average scale error (ppm)
quantumGyroMeasurementError = 0.0           # The quantum gyroscope's measurement error  (micro-radians/sec.root Hz)
quantumGyroNonOrthogonalityMean = 0.0       # The quantum gyroscope's non-orthogonal mean error (micro-radians)
quantumGyroInitialStaticBiasMean = 0.0      # The quantum gyroscope's initial static bias error(micro-radians/sec)


; --------------- Quantum IMU fusion parameters --------------- ;

;quantumImuNumParticles = 200			    # The number of particles to use for the particle filter
;quantumImuSigmaMisalignment = 0.1	        # The standard deviation for the estimated axes misalignment
;quantumImuSigmaAccelerometer = 0.1          # The sigma value to use for estimated average accelerometer bias
;quantumImuSigmaGyroscope = 0.1              # The sigma value to use for estimated average gyroscope bias

quantumImuNumParticles = 200
quantumImuSigmaMisalignment = 0.0001
quantumImuSigmaAccelerometer = 0.0001
quantumImuSigmaGyroscope = 0.0001

quantumImuMisalignment = 0.1
quantumImuHasMisalignment = no


; --------------- Quantum IMU sensor parameters --------------- ;

quantumImuNumAtoms = 1e6                    # The number of atoms in cloud to use for each measurement
quantumImuAtomMass = 2.20693925e-25         # The mass of each of the atoms (in kilograms)
quantumImuBeamWidth = 2.5                   # The interferometer beam width (metres). [Delta_x]
quantumImuLength = 2.5                      # The length of the interferometer (metres). [Delta_z]
quantumImuETA = 1.0                         # The detection efficiency for measurements. [eta]
quantumImuTimePulse = 0.25                  # The time between pulses (seconds). [T_pulse]
quantumImuAtomRecoilVec = 7.0e-3            # The recoil velocity of the cold atoms. [v_rec]
