# ------------------------------------------------------------------------------
# Example 3 - 5 degree longitude line, Perfect Sensors, No Holonomic Constraints
# ------------------------------------------------------------------------------
# Performs a straight line trajectory along the equator with theoretically
# perfect sensors, using holonomic constrains. Should filter out small
# numerical sensitivities without impacting simulation estimation accuracy.


[Output]  # Properties for controlling the output information of the software

;Should output results be saved after completion.
saveResults = yes

;Should an output figures be generated after completion.
saveFigures = yes

;Should the output figures be shown after completion.
showFigures = yes

;The save file format(s) to use for the output data.
;Use commas if selecting multiple output format types.
;(Supported: csv, csv_gz, numpy, numpy_gz, binary, mat, mat_comp)
saveFormat = csv

;The file format to use for saving generated figures.
;(Supported: png, jpg, webp, pdf)
figureFormat = png

;The backend renderer to use for displaying figures.
;(Supported: default, plotly_mimetype, browser, chrome, iframe)
figureRenderer = browser

;Should a copy of the config file be included with the output.
copyConfig = yes

;;Should the waypoint data be included in the results.
;saveTrajectory = yes

;An integer multiplier to down-sample the collected results by.
;Can be used to reduce the amount of information collected.
resultsDownSampleRate = 10

;An integer multiplier to down-sample the output files by.
;Can be used to reduce the size of additional output files.
outputDownSampleRate = 10

;The location were output results are to be written to.
;Non-existing parent directories will be created automatically.
resultsPath = output/examples/example_3_5deg_perfect/

;Should a date folder be appended to the output database_dir.
;Useful to enable if repeatedly executing the same configuration
;without needing to specify a new output database_dir.
appendDateFolder = yes

;If estimation errors are to be calculated and displayed during simulations.
calculateErrors = yes

;Time interval for console updates (given in simulated seconds).
displayInterval = 2.5

;If above enabled, will automatically stop the simulation when the position
;error of estimated state exceeds this threshold (given in metres).
;autoStopMaxEstimationError = 1000.0


# --------------------------------------------------------------------------- #

[Database]  # The location of database directories

;The location of Digital Terrain Elevation Data (DTED)
dtedDatabase = databases/dted/

;The location of Geoid data.
geoidDatabase = databases/geoid/

;The location of GPS Rinex data.
gpsDatabase = databases/gps/

;The location of Geosat44 Gravity data.
geosatGravityDatabase = databases/gravity/geosat/

;The location of Marine Gravity data.
marineGravityDatabase = databases/gravity/marine/

;The location of GGM Plus Gravity data.
ggmPlusGravityDatabase = databases/gravity/ggmPlus/

;The location of SRTM2Gravity Gravity data.
srtm2GravityDatabase = databases/gravity/srtm2gravity/

;The location of custom Irish Sea Gravity data.
irishSeaGravityDatabase = databases/gravity/irishSea/


# --------------------------------------------------------------------------- #

[Waypoints]  # Variables for waypoint (simulation) settings

;The cropped beginning simulation time (disable to use true start).
;startTime = 0.0

;The cropped ending simulation time (disable to remove limit).
;maxTime = 3600.0

;The sub-frequency for waypoint position generation.
waypointFrequency = 250

;The interpolation method to use for waypoint look-up.
;(Supported values: cubic, pchip, akima)
waypointInterpolation = pchip

;The mode to use for generating trajectory waypoints
;(Supported values: config, csv, racetrack)
waypointMode = config

;The path/waypoint sub-configuration file.
;(Ensure that the vehicle model selected is appropriate!)
waypointConfig = config/waypoints/longitude_line_5deg.ini

;Should base waypoints be read from a CSV file?
;(Overrides given waypoints)
waypointCSV = resources/waypoints/Salisbury_to_Andover.csv

;Accept CSV latitude-longitude coordinates in opposite order.
invertCSVLatLon = no

;Ignore CSV timestamp values if included in the given file.
ignoreCSVTimes = no

;;An integer multiplier to down-sample the CSV data by.
;;This can be set if points are too close together.
;csvDownSampleRate = 1

;;Should waypoints be loaded from a pre-generated file?
;;(Overrides given waypoints and CSV file)
;waypointInputFile = resources/waypoints/testing.npy
;
;;Should waypoints be saved to for reuse after generation?
;waypointsOutputFile = resources/waypoints/testing.npy

;Should vehicle properties be applied when calculating the trajectory.
;Vehicle maneuver limitations will still be applied if disabled.
;applyFullVehicleProfile = no

;Should virtual memory be used for holding the waypoint data?
;This will use disk space for reducing memory requirements.
;For 32-bit systems there is a maximum 2GB file limit!
useVirtualMemory = no


# --------------------------------------------------------------------------- #

[Racetrack]  # Optional parameters for the default race track

;Dimensions of the racetrack (in metres).
distanceX = 1000.0
distanceY = 1000.0
distanceZ = 1000.0

;The time period for one circuit of the track (in seconds).
circuitTime = 360.0

;The maximum time period for trajectory (in seconds).
maxTime = 1000.0

;The starting position on the circuit.
startX = 0.0
startY = 0.0
startZ = 0.5

;Number of periods of variations for each circuit in x.
numVariationsY = 2
numVariationsZ = 3

;Set the centre position of the racetrack.
latOrigin = 0
lonOrigin = 0
altOrigin = 100


# --------------------------------------------------------------------------- #

[Vehicle]  # Variables for vehicle settings and constraints

;Configuration file for the vehicle parameters
vehicleConfig = config/vehicles/basic.ini
;vehicleConfig = config/vehicles/large_aircraft.ini
;vehicleConfig = config/vehicles/large_van.ini
;vehicleConfig = config/vehicles/large_ship.ini
;vehicleConfig = config/vehicles/no_limits.ini

;Angles of the lever arm (in degrees).
leverArmAngleX = 0.0
leverArmAngleY = 0.0
leverArmAngleZ = 0.0

;Angles of the sensors (in degrees).
sensorAngleX = 0.0
sensorAngleY = 0.0
sensorAngleZ = 0.0


# --------------------------------------------------------------------------- #

[Gravity]  # Variables for gravity modelling

;Should missing gravity files be automatically downloaded?
autoDownload = true

;The base gravity function to use for ground truth.
;(Supported methods: fixed, uniform, wgs84, somigliana)
trueGravityFunction = somigliana

;The correction map model to use for ground truth.
;(Supported methods: none, geosat, marine, ggmPlus, srtm2gravity, irishSea)
trueGravityMapModel = none

;The down-sampling ratio to apply for ground truth correction maps.
;(Optionally can be used to reduce resolution of available data).
trueGravityDownSampling = 1

;The base gravity function to use for estimation processing.
;(Supported methods: fixed, uniform, wgs84, somigliana)
estimatedGravityFunction = somigliana

;The correction map model to use for estimation processing.
;(Supported methods: none, geosat, marine, ggmPlus, srtm2gravity, irishSea)
estimatedGravityMapModel = none

;The down-sampling ratio to apply for estimation processing correction maps.
;(Optionally can be used to reduce resolution of available data).
estimatedGravityDownSampling = 1


# --------------------------------------------------------------------------- #

[Measurement]  # Variables for exact measurement

;The IMU update frequency.
imuMeasurementFreq = 500

;The accelerometer sub-configuration files for simulation.
accelerometerConfig = config/accelerometers/perfect.ini

;The gyroscope sub-configuration files for simulation.
gyroscopeConfig = config/gyroscopes/perfect.ini

;The clock sub-configuration files for simulation.
clockConfig = config/clocks/perfect.ini


# --------------------------------------------------------------------------- #

[Estimation]  # Variables for estimation calculations

;The model to use for representing estimated state information.
;(Supported options: simple, kalman)
estimatedStateModel = simple

;The INS navigation integration method to use
;(numerical, runge_kutta, adams_bashforth or kalman).
integrationMethod = numerical

;The initial estimation errors
initialPositionErrorNorth = 0.0
initialPositionErrorEast = 0.0
initialPositionErrorDown = 0.0

initialVelocityErrorNorth = 0.0
initialVelocityErrorEast = 0.0
initialVelocityErrorDown = 0.0

initialAccelerationErrorNorth = 0.0
initialAccelerationErrorEast = 0.0
initialAccelerationErrorDown = 0.0

initialAttitudeErrorHeading = 0.0
initialAttitudeErrorPitch = 0.0
initialAttitudeErrorRoll = 0.0

initialAngleRateErrorHeading = 0.0
initialAngleRateErrorPitch = 0.0
initialAngleRateErrorRoll = 0.0

;Tunable Kalman filter process noise values.
;processNoiseAcceleration = 0.0001
;processNoiseVelocity = 0.0005
;processNoiseAngular = 0.01
;processNoiseAngleRate = 0.1

;The accelerometer sub-configuration files for estimation.
accelerometerConfig = config/accelerometers/perfect.ini

;The gyroscope sub-configuration files for estimation.
gyroscopeConfig = config/gyroscopes/perfect.ini

;The clock sub-configuration files for estimation.
clockConfig = config/clocks/perfect.ini

;Should virtual memory be used for holding the results data?
;This will use disk space for reducing memory requirements.
;For 32-bit systems there is a maximum 2GB file limit!
useVirtualMemory = no


# --------------------------------------------------------------------------- #

[Altimeter]  # Variables for the altimeter

;Is the altimeter enabled?
altimeterEnabled = no

;The altimeter sub-configuration files for simulation.
altimeterConfig = config/altimeters/perfect.ini

;The fusion method to use for altimeter measurements.
;(Supported methods: fixed_gain, alpha_beta)
altimeterFusion = alpha_beta

;The fixed gain amount to use for fixed-gain filtering.
altimeterGainAmount = 0.1

;The alpha value to use for alpha-beta filtering.
altimeterAlphaAmount = 0.9

;The beta value to use for alpha-beta filtering.
;(If not provided a suitable value will be automatically assigned)
altimeterBetaAmount = 0.05

;Should the beat value for alpha-beta filtering be automatically selected?
altimeterAutoSetBeta = false

# --------------------------------------------------------------------------- #

[GPS]  # Variables for the GPS and satellite settings

;Should GPS systems be enabled?
gpsEnabled = no

;Whether GPS data is to be automatically downloaded.
gpsAutoDownload = yes

;The GPS time (year, month and day) to use.
gpsTimeYear = 2019
gpsTimeMonth = 2
gpsTimeDay = 25

;The GPS update frequency.
gpsMeasurementFreq = 1.0

;The GPS noise values.
gpsRhoNoise = 0
gpsRhoRateNoise = 0

;The CSV file used to specify the deactivation zones for the GPS.
;(In the format 'lat1, lon1, lat2, lon2' with each shape being on a line)
;gpsDisabledZonesCSV = config/gps_zones/liverpool.csv   # Not yet supported

;The CSV file used to specify the activation zones for the GPS.
;(In the format 'lat1, lon1, lat2, lon2' with each shape being on a line)
;gpsEnabledZonesCSV = config/gps_zones/preston.csv    # Not yet supported

;The GPS fusion method to use (fixed_gain, loose or tight).
gpsFusionMethod = fixed_gain

;If fixed gain fusion is enabled, this will be the gain factor.
gpsFixedGain = 5e-2

;The number of tuning iterations to perform on start-up.
gpsInitIterations = 3

;The pseudo-range position error (in metres) for loosely coupled fusion.
gpsSigmaPosition = 1

;The pseudo-range velocity error (in metres/sec) for loosely coupled fusion.
gpsSigmaVelocity = 0.3


# --------------------------------------------------------------------------- #

[Quantum]  # Variables for the quantum sensors

;Should the quantum IMU be used?
quantumImuEnabled = no

;The type of quantum inertia sensor to use
;(Supported methods: concept, realistic)
quantumImuSensor = realistic

;The fusion method to use for the quantum
;(Supported methods: basic, particle_filter, misaligned)
quantumImuFusion = basic

;The quantum IMU sub-configuration file.
quantumImuConfig = config/quantum_imu/custom.ini


;;Should the quantum gravity map-matcher be used?  # Not yet supported
;quantumGravityEnabled = no
;
;;The type of quantum gravity sensor to use  # Not yet supported
;;(Supported methods: concept)
;quantumGravitySensor = concept
;
;;The fusion method to use for the quantum gravity map-matching  # Not yet supported
;;(Supported methods: basic)
;quantumGravityFusion = basic
;
;;The quantum gravity map-matching sub-configuration file.  # Not yet supported
;quantumGravityConfig = config/quantum_gravity/custom.ini


# --------------------------------------------------------------------------- #

[Holonomics]  # Variables for controlling holonomic constraints

;Should holonomic constraints be used?
;(Will help will unwanted numerical sensitivities)
useHolonomics = no

;The update rate at which corrections are applied (in Hz).
correctionFreq = 1

;Holonomic gain and axis percentages for position.
;(Set gain to 0 to disable. Axis in latitude-longitude-altitude).
positionGain = 0
positionAxis = 1,1,1

;Holonomic gain and axis percentages for velocity.
;(Set gain to 0 to disable. Axis in body along-across-down).
velocityGain = 0
velocityAxis = 1,1,1

;Holonomic gain and axis percentages for acceleration.
;(Set gain to 0 to disable. Axis in body along-across-down).
accelerationGain = 0
accelerationAxis = 1,1,1

;Holonomic gain and axis percentages for attitude.
;(Set gain to 0 to disable. Axis in PQR euler angles).
attitudeGain = 0
attitudeAxis = 1,1,1

;Holonomic gain and axis percentages for angle rates.
;(Set gain to 0 to disable. Axis in PQR euler angle rates).
angleRateGain = 0
angleRateAxis = 1,1,1


# --------------------------------------------------------------------------- #

[Random]  # Variables for controlling random number generation

;The random seed for initialising random parameters.
initialRandomSeed = 0
autoGenerateInitialSeed = no

;The random seed for vehicle movement, vibrations and noise.
waypointRandomSeed = 0
autoGenerateWaypointSeed = no

;The random seed for simulation randomness (noise, drift, errors).
simulationRandomSeed = 0
autoGenerateSimulationSeed = no

;The random seed for simulation randomness (noise, drift, errors).
errorRandomSeed = 0
autoGenerateErrorSeed = no


# --------------------------------------------------------------------------- #

[Misc]  # Additional miscellaneous variables

;If variables read from sub-configurations are to overwrite existing values.
;If set to No (default) values present in this file will overwrite those
;extracted from sub-configuration files.
allowConfigOverloading = no

;If warnings are to be displayed about values missing from the configuration.
;This is useful for debugging purposes where automatic changes are declared.
displayFallbackWarnings = no

;Should resource auditing be performed (requires external scripts).
performAuditing = no

;The file name to use for the auditing log.
;If the file already exists new records will be appended to it.
auditLoggingFile = audit.csv
