# --------------------------------------------------------------------------- #
#                        QUANTUM GRAVIMETER SETTINGS                          #
# --------------------------------------------------------------------------- #
# This settings file contains the configuration values for the quantum        #
# gravimeter sensor and connected fusion method.                              #
# --------------------------------------------------------------------------- #

[Quantum]

; ----------------- Quantum gravimeter timing parameters  ----------------- ;

quantumGravFrequency = 0.7		            # The total operating frequency of the sensor (Hz).
quantumGravDutyCycle = 0.005		            # Percentage of time the sensor is active (measuring).

; --------------- Quantum gravity interferometer parameters ---------------- ;

quantumGravNumAtoms = 200000                # The number of atoms to use for each measurement
quantumGravAtomMass = 1.4431608262e-25      # The mass of each of the atoms (in kilograms)
quantumGravRecoilVelocity = 5.8845e-3       # The recoil velocity of the cold atoms when absorbing/emitting a photon
quantumGravStationaryVelocity = 1.57        # Average vertical velocity of the atoms when the system is stationary (m/s)
quantumGravSensorZTop = 0.0                 # First height offset of interferometer sensor (m)
quantumGravSensorZBottom = -1.0             # Second height offset of interferometer sensor (m)
quantumGravEta = 0.25                       # The detection efficiency for measurements (decimal percentage)
quantumGravTimePulse = 0.2                  # The time between measurement pulses (in seconds)
quantumGravSigmaPhi = 0.0                 # Relative phase noise for between paired interferometers
quantumGravSigmaN = 0.0                     # Relative scale of white noise for each interferometers (NEW).
quantumGravBeamWidth = 0.01                 # Interferometer beam width (metres)
quantumGravSensorLength = 1.0               # Length of interferometer (metres)
quantumGravRandFailureProb = 0.0            # Probability for purely random measurement failure

; ---------------- Gravity accelerometer sensor parameters ----------------- ;

quantumGravBiasDriftRate = 0.0               # The quantum accelerometer's drift rate (micro-g/root sec)
quantumGravScaleErrorMean = 0.0              # The quantum accelerometer's average scale error (ppm)
quantumGravMeasurementError = 0.0            # The quantum accelerometer's measurement error (micro-g.root Hz)
quantumGravNonOrthogonalityMean = 0.0        # The quantum accelerometer's non-orthogonal mean error (micro-radians)
quantumGravInitialStaticBiasMean = 0.0       # The quantum accelerometer's initial static bias error (micro-radians/sec)


; --------------- Quantum gravity particle filter parameters --------------- ;

quantumGravFusionNumParticles = 3000         # The number of particles to use for the particle filter

quantumGravFusionInitPositionSigma = 40.0    # The standard deviation for initial position estimation (metres)
quantumGravFusionInitVelocitySigma = 0        # The standard deviation for initial velocity estimation (m/s)
quantumGravFusionInitAttitudeSigma = 0        # The standard deviation for initial attitude estimation (deg)

quantumGravFusionWeightSigma = 1e-5           # The standard deviation used when resampling

quantumGravFusionAlphaSigma = 0.5            # The gain percentage applied for position estimations (metres)
quantumGravFusionBetaSigma = 0.00            # The gain percentage applied for velocity estimations (m/s)
quantumGravFusionGammaSigma = 0.00           # The gain percentage applied for attitude estimations (deg)

quantumGravFusionPositionSigma = 1.0         # The standard deviation for position estimation (metres)
quantumGravFusionVelocitySigma = 0.0         # The standard deviation for velocity estimation (m/s)
quantumGravFusionAttitudeSigma = 0.0         # The standard deviation for attitude estimation (deg)

quantumGravFusionEllipseIntervals = 361      # The number of intervals on ellipse to measure distance from
quantumGravFusionEllipseIterations = 5       # The number of times ellipse fitting shall be performed/optimised
