# --------------------------------------------------------------------------- #
#                         GYROSCOPE SETTINGS - AVIATION                       #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for a         #
# gyroscope. This given configuration is used to simulate the accuracy        #
# expected from aviation graded hardware.                                     #
# --------------------------------------------------------------------------- #

[Gyroscope]
gyroscopeBiasDriftRate = 0.005                    	# (micro-rad/sec.root sec)
gyroscopeScaleErrorMean = 10                    	# (ppm) [expected: 25-50]
gyroscopeMeasurementError = 20                 		# (micro-radians/sec.root Hz)
gyroscopeNonOrthogonalityMean = 10             		# (micro-radians)
gyroscopeInitialStaticBiasMean = 0.05            	# (micro-radians/sec)
