# Experimental aviation grade settings

[Gyroscope]
gyroscopeBiasDriftRate = 0.0                    	# (micro-rad/sec.root sec)
gyroscopeScaleErrorMean = 0.0                    	# (ppm) [expected: 25-50]
gyroscopeMeasurementError = 10                 		# (micro-radians/sec.root Hz)
gyroscopeNonOrthogonalityMean = 0.0                 # (micro-radians)
gyroscopeInitialStaticBiasMean = 0.05            	# (micro-radians/sec)
