# --------------------------------------------------------------------------- #
#                         GYROSCOPE SETTINGS - CONSUMER                       #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for a         #
# gyroscope. This given configuration is used to simulate the accuracy        #
# expected from consumer graded hardware.                                     #
# --------------------------------------------------------------------------- #

[Gyroscope]
gyroscopeBiasDriftRate = 20.0                    	# (micro-rad/sec.root sec)
gyroscopeScaleErrorMean = 2000                    	# (ppm)
gyroscopeMeasurementError = 1000                 	# (micro-radians/sec.root Hz)
gyroscopeNonOrthogonalityMean = 2000             	# (micro-radians)
gyroscopeInitialStaticBiasMean = 500            	# (micro-radians/sec)
