# --------------------------------------------------------------------------- #
#                       GYROSCOPE SETTINGS - INTERMEDIATE                     #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for a         #
# gyroscope. This given configuration is used to simulate the accuracy        #
# expected from intermediate (between Aviation and Tactical) graded hardware. #
# --------------------------------------------------------------------------- #

[Gyroscope]
gyroscopeBiasDriftRate = 0.05                    	# (micro-rad/sec.root sec)
gyroscopeScaleErrorMean = 100                    	# (ppm) [expected: 50-100]
gyroscopeMeasurementError = 60                 		# (micro-radians/sec.root Hz)
gyroscopeNonOrthogonalityMean = 100             	# (micro-radians)
gyroscopeInitialStaticBiasMean = 0.5            	# (micro-radians/sec)
