# --------------------------------------------------------------------------- #
#                          GYROSCOPE SETTINGS - MARINE                        #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for a         #
# gyroscope. This given configuration is used to simulate the accuracy        #
# expected from marine graded hardware.                                       #
# --------------------------------------------------------------------------- #

[Gyroscope]
gyroscopeBiasDriftRate = 0.0005                    	# (micro-rad/sec.root sec)
gyroscopeScaleErrorMean = 10                    	# (ppm)
gyroscopeMeasurementError = 10                  	# (micro-radians/sec.root Hz)
gyroscopeNonOrthogonalityMean = 10              	# (micro-radians)
gyroscopeInitialStaticBiasMean = 0.005          	# (micro-radians/sec)
