# --------------------------------------------------------------------------- #
#                         GYROSCOPE SETTINGS - TACTICAL                       #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for a         #
# gyroscope. This given configuration is used to simulate the accuracy        #
# expected from tactical graded hardware.                                     #
# --------------------------------------------------------------------------- #

[Gyroscope]
gyroscopeBiasDriftRate = 1.0                    	# (micro-rad/sec.root sec)
gyroscopeScaleErrorMean = 250                    	# (ppm) [expected: 100-500]
gyroscopeMeasurementError = 100                 	# (micro-radians/sec.root Hz)
gyroscopeNonOrthogonalityMean = 250             	# (micro-radians)
gyroscopeInitialStaticBiasMean = 10.0            	# (micro-radians/sec)
