# --------------------------------------------------------------------------- #
#                           IRISH SEA - EXAMPLE PATH                          #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed.                   #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 55, 55.5, 54.5, 53, 52.5, 53.5, 54.5
waypointLon = -25, -22, -21.5, -21.25, -24, -25.5, -25.5
waypointAlt = 1000, 1000, 1000, 1000, 1000, 1000, 1000
