# --------------------------------------------------------------------------- #
#                           Example Waypoint Path                             #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed. This route can be #
# described by visiting the following locations:                              #
#                                                                             #
#            Leeds --> Manchester --> Warrington --> Liverpool                #
#                    --> Manchester --> Sheffield                             #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 53.800950, 53.481166, 53.386695, 53.411640, 53.481166, 53.378079
waypointLon = -1.538822, -2.235227, -2.599161, -3.000065, -2.235227, -1.474052
waypointAlt = 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0


;53.800950, -1.538822
;53.481166, -2.235227
;53.386695, -2.599161
;53.411640, -3.000065
;53.481166, -2.235227
;53.378079, -1.474052
