# --------------------------------------------------------------------------- #
#                           Example Waypoint Path 3                           #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed. This route can be #
# described by visiting the following locations:                              #
#                                                                             #
#     Liverpool --> York --> Newcastle --> Liverpool                         #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 53.407579, 53.958333, 55.007700, 53.407579
waypointLon = -2.967853, -1.080278, -1.657800, -2.967853
waypointAlt = 1000.0, 1000.0, 1000.0, 1000.0