# --------------------------------------------------------------------------- #
#                           Example Waypoint Path 3                           #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed.                   #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 53.759, 53.406725, 53.479444, 53.799722, 53.383333, 53.479444, 53.759
waypointLon = -2.699, -2.966751, -2.245278, -1.549167, -1.466667, -2.245278, -2.699
waypointAlt = 1000, 1250, 1200, 1100, 900, 1200, 1000
