# --------------------------------------------------------------------------- #
#                           Example Waypoint Path 1                           #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed. This route can be #
# described by visiting the following locations:                              #
#                                                                             #
#     Liverpool --> Chelmsford --> Noordwijk --> Liverpool                    #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 53.407579, 51.730953, 52.217604, 53.407579
waypointLon = -2.967853, 0.457221, 4.419805, -2.967853
waypointAlt = 1000, 1000, 1000, 1000