# --------------------------------------------------------------------------- #
#                           Example Waypoint Path 2                           #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed. This route can be #
# described by visiting the following locations:                              #
#                                                                             #
#     Liverpool --> Warrington --> Preston --> Liverpool                      #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 53.407579, 53.410000, 53.700000, 53.407579
waypointLon = -2.967853, -2.70000, -2.80000, -2.967853
waypointAlt = 1000.0, 1000.0, 1000.0, 1000.0