# --------------------------------------------------------------------------- #
#                           Example Waypoint Path 5                           #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed. This route can be #
# described by visiting the following locations:                              #
#                                                                             #
#     Liverpool --> York                                                      #
# --------------------------------------------------------------------------- #

[Waypoints]
waypointLat = 53.407579, 53.958333
waypointLon = -2.967853, -1.080278
waypointAlt = 1000.0, 1000.0

;waypointLat = 53.407579, 53.4075791
;waypointLon = -2.967853, -2.9678528
;waypointAlt = 1000.0, 1000.0

;waypointLat = 53.407579, 53.407579061212935
;waypointLon = -2.967853, -2.967852798345083
;waypointAlt = 1000.0, 1000.0