# --------------------------------------------------------------------------- #
#                           Example Waypoint Path                             #
# --------------------------------------------------------------------------- #
# This files contains a series of waypoint coordinates (latitude, longitude   #
# and altitude) outlining a projected route to be followed. This route can be #
# described by visiting the following locations:                              #
#                                                                             #
#     Manchester --> Birmingham                                                #
# --------------------------------------------------------------------------- #

[Waypoints]

; Short Manchester (5 metres east drift)
waypointLat = 53.483908, 53.483908
waypointLon = -2.249165, -2.24908968
waypointAlt = 100.0, 100.0