[RawData]
file = ../../raw_data_example_1/imu_clean.csv
timeUnit = s
chunkSize = 100000
invalidRecordPolicy = strict
imuInputLevel = truth

[RawInitialState]
# First ground_truth.csv record. Quaternion converted from WXYZ to HPR degrees.
latitude = 52.8
longitude = -15.3
altitude = 59.8323447429002
velocityX = 0.000001
velocityY = 0
velocityZ = 0
accelerationX = -0.0435533973649468
accelerationY = -0.0156975711927362
accelerationZ = -9.81313513345626
heading = 22.5
pitch = 0.000939287506
roll = -0.00284520098
angularRateX = 0.0023338296325084705
angularRateY = -0.000966275921882056
angularRateZ = -0.0033279708295355327

[RawAccelerometer]
timestampColumn = time [s]
xColumn = ax [m/s2]
yColumn = ay [m/s2]
zColumn = az [m/s2]
accelerationUnits = m/s2
frame = body

[RawGyroscope]
timestampColumn = time [s]
xColumn = p [rad/s]
yColumn = q [rad/s]
zColumn = r [rad/s]
angularRateUnits = rad/s
frame = body
