# --------------------------------------------------------------------------- #
#                         ALTIMETER SETTINGS - PERFECT                        #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for an        # 
# altimeter. This given configuration is used to simulate perfect accuracy    #
# with no error growth. While unrealistic, this model is ideal for testing    #
# and comparing other configurations.                                         #
# --------------------------------------------------------------------------- #

[Altimeter]
;altimeterEnabled = no
altimeterGainAmount = 0.1									# (fixed gain filter amount)
altimeterBiasDriftRate = 0.0                             	# (metres/root sec)
altimeterMeasurementFreq = 1.0                           	# (hz)
altimeterMeasurementError = 0.0                          	# (metres)
altimeterInitialStaticBiasMean = 0.0                     	# (metres above sea level)
