# --------------------------------------------------------------------------- #
#                          ALTIMETER SETTINGS - TACTICAL                      #
# --------------------------------------------------------------------------- #
# This settings file contains the hardware configuration values for an        # 
# altimeter. This given configuration is used to simulate the accuracy        #
# expected from tactical graded hardware.                                     #
# --------------------------------------------------------------------------- #

[Altimeter]
;altimeterEnabled = no
altimeterGainAmount = 0.1									# (fixed gain filter amount)
altimeterBiasDriftRate = 0.0                             	# (metres/root sec)
altimeterMeasurementFreq = 0.0                           	# (hz)
altimeterMeasurementError = 0.0                          	# (metres)
altimeterInitialStaticBiasMean = 0.0                     	# (metres above sea level)
